network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ens18: #or any other interface name
      addresses:
        - [IP]/[subnet]
      gateway4: [router_IP] #router ip
      nameservers:
        addresses: [[NS_ip],[NS2_ip],.[..]] #for static dns config
